# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /local/ssd-scratch/tkeck/externals/v01-01-01/Linux_x86_64/common/bin/cmake

# The command to remove a file.
RM = /local/ssd-scratch/tkeck/externals/v01-01-01/Linux_x86_64/common/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /local/ssd-scratch/tkeck/FastBDT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /local/ssd-scratch/tkeck/FastBDT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/local/ssd-scratch/tkeck/externals/v01-01-01/Linux_x86_64/common/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/local/ssd-scratch/tkeck/externals/v01-01-01/Linux_x86_64/common/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/local/ssd-scratch/tkeck/externals/v01-01-01/Linux_x86_64/common/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/local/ssd-scratch/tkeck/externals/v01-01-01/Linux_x86_64/common/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/local/ssd-scratch/tkeck/externals/v01-01-01/Linux_x86_64/common/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/local/ssd-scratch/tkeck/externals/v01-01-01/Linux_x86_64/common/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /local/ssd-scratch/tkeck/FastBDT/CMakeFiles /local/ssd-scratch/tkeck/FastBDT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /local/ssd-scratch/tkeck/FastBDT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FastBDT

# Build rule for target.
FastBDT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FastBDT
.PHONY : FastBDT

# fast build rule for target.
FastBDT/fast:
	$(MAKE) -f CMakeFiles/FastBDT.dir/build.make CMakeFiles/FastBDT.dir/build
.PHONY : FastBDT/fast

#=============================================================================
# Target rules for targets named FastBDTMain

# Build rule for target.
FastBDTMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FastBDTMain
.PHONY : FastBDTMain

# fast build rule for target.
FastBDTMain/fast:
	$(MAKE) -f CMakeFiles/FastBDTMain.dir/build.make CMakeFiles/FastBDTMain.dir/build
.PHONY : FastBDTMain/fast

#=============================================================================
# Target rules for targets named FastBDT_CInterface

# Build rule for target.
FastBDT_CInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FastBDT_CInterface
.PHONY : FastBDT_CInterface

# fast build rule for target.
FastBDT_CInterface/fast:
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/build
.PHONY : FastBDT_CInterface/fast

#=============================================================================
# Target rules for targets named TMVAFastBDT

# Build rule for target.
TMVAFastBDT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TMVAFastBDT
.PHONY : TMVAFastBDT

# fast build rule for target.
TMVAFastBDT/fast:
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/build
.PHONY : TMVAFastBDT/fast

#=============================================================================
# Target rules for targets named TMVAFastBDT_Dict

# Build rule for target.
TMVAFastBDT_Dict: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TMVAFastBDT_Dict
.PHONY : TMVAFastBDT_Dict

# fast build rule for target.
TMVAFastBDT_Dict/fast:
	$(MAKE) -f CMakeFiles/TMVAFastBDT_Dict.dir/build.make CMakeFiles/TMVAFastBDT_Dict.dir/build
.PHONY : TMVAFastBDT_Dict/fast

#=============================================================================
# Target rules for targets named unittests

# Build rule for target.
unittests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittests
.PHONY : unittests

# fast build rule for target.
unittests/fast:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/build
.PHONY : unittests/fast

src/FastBDT.o: src/FastBDT.cxx.o

.PHONY : src/FastBDT.o

# target to build an object file
src/FastBDT.cxx.o:
	$(MAKE) -f CMakeFiles/FastBDT.dir/build.make CMakeFiles/FastBDT.dir/src/FastBDT.cxx.o
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/src/FastBDT.cxx.o
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/src/FastBDT.cxx.o
.PHONY : src/FastBDT.cxx.o

src/FastBDT.i: src/FastBDT.cxx.i

.PHONY : src/FastBDT.i

# target to preprocess a source file
src/FastBDT.cxx.i:
	$(MAKE) -f CMakeFiles/FastBDT.dir/build.make CMakeFiles/FastBDT.dir/src/FastBDT.cxx.i
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/src/FastBDT.cxx.i
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/src/FastBDT.cxx.i
.PHONY : src/FastBDT.cxx.i

src/FastBDT.s: src/FastBDT.cxx.s

.PHONY : src/FastBDT.s

# target to generate assembly for a file
src/FastBDT.cxx.s:
	$(MAKE) -f CMakeFiles/FastBDT.dir/build.make CMakeFiles/FastBDT.dir/src/FastBDT.cxx.s
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/src/FastBDT.cxx.s
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/src/FastBDT.cxx.s
.PHONY : src/FastBDT.cxx.s

src/IO.o: src/IO.cxx.o

.PHONY : src/IO.o

# target to build an object file
src/IO.cxx.o:
	$(MAKE) -f CMakeFiles/FastBDT.dir/build.make CMakeFiles/FastBDT.dir/src/IO.cxx.o
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/src/IO.cxx.o
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/src/IO.cxx.o
.PHONY : src/IO.cxx.o

src/IO.i: src/IO.cxx.i

.PHONY : src/IO.i

# target to preprocess a source file
src/IO.cxx.i:
	$(MAKE) -f CMakeFiles/FastBDT.dir/build.make CMakeFiles/FastBDT.dir/src/IO.cxx.i
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/src/IO.cxx.i
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/src/IO.cxx.i
.PHONY : src/IO.cxx.i

src/IO.s: src/IO.cxx.s

.PHONY : src/IO.s

# target to generate assembly for a file
src/IO.cxx.s:
	$(MAKE) -f CMakeFiles/FastBDT.dir/build.make CMakeFiles/FastBDT.dir/src/IO.cxx.s
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/src/IO.cxx.s
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/src/IO.cxx.s
.PHONY : src/IO.cxx.s

src/MethodFastBDT.o: src/MethodFastBDT.cxx.o

.PHONY : src/MethodFastBDT.o

# target to build an object file
src/MethodFastBDT.cxx.o:
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/src/MethodFastBDT.cxx.o
.PHONY : src/MethodFastBDT.cxx.o

src/MethodFastBDT.i: src/MethodFastBDT.cxx.i

.PHONY : src/MethodFastBDT.i

# target to preprocess a source file
src/MethodFastBDT.cxx.i:
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/src/MethodFastBDT.cxx.i
.PHONY : src/MethodFastBDT.cxx.i

src/MethodFastBDT.s: src/MethodFastBDT.cxx.s

.PHONY : src/MethodFastBDT.s

# target to generate assembly for a file
src/MethodFastBDT.cxx.s:
	$(MAKE) -f CMakeFiles/TMVAFastBDT.dir/build.make CMakeFiles/TMVAFastBDT.dir/src/MethodFastBDT.cxx.s
.PHONY : src/MethodFastBDT.cxx.s

src/c_interface.o: src/c_interface.cxx.o

.PHONY : src/c_interface.o

# target to build an object file
src/c_interface.cxx.o:
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/src/c_interface.cxx.o
.PHONY : src/c_interface.cxx.o

src/c_interface.i: src/c_interface.cxx.i

.PHONY : src/c_interface.i

# target to preprocess a source file
src/c_interface.cxx.i:
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/src/c_interface.cxx.i
.PHONY : src/c_interface.cxx.i

src/c_interface.s: src/c_interface.cxx.s

.PHONY : src/c_interface.s

# target to generate assembly for a file
src/c_interface.cxx.s:
	$(MAKE) -f CMakeFiles/FastBDT_CInterface.dir/build.make CMakeFiles/FastBDT_CInterface.dir/src/c_interface.cxx.s
.PHONY : src/c_interface.cxx.s

src/main.o: src/main.cxx.o

.PHONY : src/main.o

# target to build an object file
src/main.cxx.o:
	$(MAKE) -f CMakeFiles/FastBDTMain.dir/build.make CMakeFiles/FastBDTMain.dir/src/main.cxx.o
.PHONY : src/main.cxx.o

src/main.i: src/main.cxx.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cxx.i:
	$(MAKE) -f CMakeFiles/FastBDTMain.dir/build.make CMakeFiles/FastBDTMain.dir/src/main.cxx.i
.PHONY : src/main.cxx.i

src/main.s: src/main.cxx.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cxx.s:
	$(MAKE) -f CMakeFiles/FastBDTMain.dir/build.make CMakeFiles/FastBDTMain.dir/src/main.cxx.s
.PHONY : src/main.cxx.s

src/tests.o: src/tests.cxx.o

.PHONY : src/tests.o

# target to build an object file
src/tests.cxx.o:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/tests.cxx.o
.PHONY : src/tests.cxx.o

src/tests.i: src/tests.cxx.i

.PHONY : src/tests.i

# target to preprocess a source file
src/tests.cxx.i:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/tests.cxx.i
.PHONY : src/tests.cxx.i

src/tests.s: src/tests.cxx.s

.PHONY : src/tests.s

# target to generate assembly for a file
src/tests.cxx.s:
	$(MAKE) -f CMakeFiles/unittests.dir/build.make CMakeFiles/unittests.dir/src/tests.cxx.s
.PHONY : src/tests.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... FastBDT_CInterface"
	@echo "... rebuild_cache"
	@echo "... unittests"
	@echo "... FastBDT"
	@echo "... TMVAFastBDT_Dict"
	@echo "... FastBDTMain"
	@echo "... TMVAFastBDT"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... src/FastBDT.o"
	@echo "... src/FastBDT.i"
	@echo "... src/FastBDT.s"
	@echo "... src/IO.o"
	@echo "... src/IO.i"
	@echo "... src/IO.s"
	@echo "... src/MethodFastBDT.o"
	@echo "... src/MethodFastBDT.i"
	@echo "... src/MethodFastBDT.s"
	@echo "... src/c_interface.o"
	@echo "... src/c_interface.i"
	@echo "... src/c_interface.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tests.o"
	@echo "... src/tests.i"
	@echo "... src/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

